name: Semantic-Release

on:
  pull_request:
  push:
    branches: [ master ]

jobs:  
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install
        run: npm ci

      - name: Install tfx-cli
        run: sudo npm install -g tfx-cli
        
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        
      - name: Upload to Visual Studio Marketplace
        run: tfx extension publish --token ${{ secrets.VS_MARKETPLACE }}